// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PulsePath.Infrastructure.Data;

#nullable disable

namespace PulsePath.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525075529_AddUserAndProfileTables")]
    partial class AddUserAndProfileTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("PulsePath_Engine_DotNet.Models.DailyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaloriesIn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FastingValidated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProteinsIn")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SleepHours")
                        .HasColumnType("REAL");

                    b.Property<int>("Steps")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkoutsDone")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DailyLogs");
                });

            modelBuilder.Entity("PulsePath_Engine_DotNet.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PulsePath_Engine_DotNet.Models.UserProfileEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<double>("ActivityFactor")
                        .HasColumnType("REAL");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BiologicalSex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("CurrentWeightKg")
                        .HasColumnType("REAL");

                    b.Property<double>("HeightCm")
                        .HasColumnType("REAL");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("PulsePath_Engine_DotNet.Models.UserProfileEntity", b =>
                {
                    b.HasOne("PulsePath_Engine_DotNet.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("PulsePath_Engine_DotNet.Models.UserProfileEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PulsePath_Engine_DotNet.Models.User", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
